// Generated by gencpp from file delivery_system/ExceptionHandleRequest.msg
// DO NOT EDIT!


#ifndef DELIVERY_SYSTEM_MESSAGE_EXCEPTIONHANDLEREQUEST_H
#define DELIVERY_SYSTEM_MESSAGE_EXCEPTIONHANDLEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delivery_system
{
template <class ContainerAllocator>
struct ExceptionHandleRequest_
{
  typedef ExceptionHandleRequest_<ContainerAllocator> Type;

  ExceptionHandleRequest_()
    : error_message()  {
    }
  ExceptionHandleRequest_(const ContainerAllocator& _alloc)
    : error_message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _error_message_type;
  _error_message_type error_message;





  typedef boost::shared_ptr< ::delivery_system::ExceptionHandleRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delivery_system::ExceptionHandleRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExceptionHandleRequest_

typedef ::delivery_system::ExceptionHandleRequest_<std::allocator<void> > ExceptionHandleRequest;

typedef boost::shared_ptr< ::delivery_system::ExceptionHandleRequest > ExceptionHandleRequestPtr;
typedef boost::shared_ptr< ::delivery_system::ExceptionHandleRequest const> ExceptionHandleRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delivery_system::ExceptionHandleRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delivery_system::ExceptionHandleRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delivery_system::ExceptionHandleRequest_<ContainerAllocator1> & lhs, const ::delivery_system::ExceptionHandleRequest_<ContainerAllocator2> & rhs)
{
  return lhs.error_message == rhs.error_message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delivery_system::ExceptionHandleRequest_<ContainerAllocator1> & lhs, const ::delivery_system::ExceptionHandleRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delivery_system

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delivery_system::ExceptionHandleRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery_system::ExceptionHandleRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery_system::ExceptionHandleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery_system::ExceptionHandleRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_system::ExceptionHandleRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_system::ExceptionHandleRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delivery_system::ExceptionHandleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a13979422fc129b30b15994450a302b5";
  }

  static const char* value(const ::delivery_system::ExceptionHandleRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa13979422fc129b3ULL;
  static const uint64_t static_value2 = 0x0b15994450a302b5ULL;
};

template<class ContainerAllocator>
struct DataType< ::delivery_system::ExceptionHandleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delivery_system/ExceptionHandleRequest";
  }

  static const char* value(const ::delivery_system::ExceptionHandleRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delivery_system::ExceptionHandleRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 请求：异常信息\n"
"string error_message        # 异常描述\n"
;
  }

  static const char* value(const ::delivery_system::ExceptionHandleRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delivery_system::ExceptionHandleRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExceptionHandleRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delivery_system::ExceptionHandleRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delivery_system::ExceptionHandleRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "error_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.error_message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELIVERY_SYSTEM_MESSAGE_EXCEPTIONHANDLEREQUEST_H
