// Generated by gencpp from file delivery_system/ExceptionHandle.msg
// DO NOT EDIT!


#ifndef DELIVERY_SYSTEM_MESSAGE_EXCEPTIONHANDLE_H
#define DELIVERY_SYSTEM_MESSAGE_EXCEPTIONHANDLE_H

#include <ros/service_traits.h>


#include <delivery_system/ExceptionHandleRequest.h>
#include <delivery_system/ExceptionHandleResponse.h>


namespace delivery_system
{

struct ExceptionHandle
{

typedef ExceptionHandleRequest Request;
typedef ExceptionHandleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExceptionHandle
} // namespace delivery_system


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::delivery_system::ExceptionHandle > {
  static const char* value()
  {
    return "c329e5e72dfc46d2450f46599776c96c";
  }

  static const char* value(const ::delivery_system::ExceptionHandle&) { return value(); }
};

template<>
struct DataType< ::delivery_system::ExceptionHandle > {
  static const char* value()
  {
    return "delivery_system/ExceptionHandle";
  }

  static const char* value(const ::delivery_system::ExceptionHandle&) { return value(); }
};


// service_traits::MD5Sum< ::delivery_system::ExceptionHandleRequest> should match
// service_traits::MD5Sum< ::delivery_system::ExceptionHandle >
template<>
struct MD5Sum< ::delivery_system::ExceptionHandleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::delivery_system::ExceptionHandle >::value();
  }
  static const char* value(const ::delivery_system::ExceptionHandleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::delivery_system::ExceptionHandleRequest> should match
// service_traits::DataType< ::delivery_system::ExceptionHandle >
template<>
struct DataType< ::delivery_system::ExceptionHandleRequest>
{
  static const char* value()
  {
    return DataType< ::delivery_system::ExceptionHandle >::value();
  }
  static const char* value(const ::delivery_system::ExceptionHandleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::delivery_system::ExceptionHandleResponse> should match
// service_traits::MD5Sum< ::delivery_system::ExceptionHandle >
template<>
struct MD5Sum< ::delivery_system::ExceptionHandleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::delivery_system::ExceptionHandle >::value();
  }
  static const char* value(const ::delivery_system::ExceptionHandleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::delivery_system::ExceptionHandleResponse> should match
// service_traits::DataType< ::delivery_system::ExceptionHandle >
template<>
struct DataType< ::delivery_system::ExceptionHandleResponse>
{
  static const char* value()
  {
    return DataType< ::delivery_system::ExceptionHandle >::value();
  }
  static const char* value(const ::delivery_system::ExceptionHandleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DELIVERY_SYSTEM_MESSAGE_EXCEPTIONHANDLE_H
