// Generated by gencpp from file delivery_system/ExceptionHandleResponse.msg
// DO NOT EDIT!


#ifndef DELIVERY_SYSTEM_MESSAGE_EXCEPTIONHANDLERESPONSE_H
#define DELIVERY_SYSTEM_MESSAGE_EXCEPTIONHANDLERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delivery_system
{
template <class ContainerAllocator>
struct ExceptionHandleResponse_
{
  typedef ExceptionHandleResponse_<ContainerAllocator> Type;

  ExceptionHandleResponse_()
    : confirm_continue(false)  {
    }
  ExceptionHandleResponse_(const ContainerAllocator& _alloc)
    : confirm_continue(false)  {
  (void)_alloc;
    }



   typedef uint8_t _confirm_continue_type;
  _confirm_continue_type confirm_continue;





  typedef boost::shared_ptr< ::delivery_system::ExceptionHandleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delivery_system::ExceptionHandleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ExceptionHandleResponse_

typedef ::delivery_system::ExceptionHandleResponse_<std::allocator<void> > ExceptionHandleResponse;

typedef boost::shared_ptr< ::delivery_system::ExceptionHandleResponse > ExceptionHandleResponsePtr;
typedef boost::shared_ptr< ::delivery_system::ExceptionHandleResponse const> ExceptionHandleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delivery_system::ExceptionHandleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delivery_system::ExceptionHandleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delivery_system::ExceptionHandleResponse_<ContainerAllocator1> & lhs, const ::delivery_system::ExceptionHandleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.confirm_continue == rhs.confirm_continue;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delivery_system::ExceptionHandleResponse_<ContainerAllocator1> & lhs, const ::delivery_system::ExceptionHandleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delivery_system

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delivery_system::ExceptionHandleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery_system::ExceptionHandleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery_system::ExceptionHandleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery_system::ExceptionHandleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_system::ExceptionHandleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_system::ExceptionHandleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delivery_system::ExceptionHandleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c7c513c4506e8c5d9151c84ecc9ad42";
  }

  static const char* value(const ::delivery_system::ExceptionHandleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c7c513c4506e8c5ULL;
  static const uint64_t static_value2 = 0xd9151c84ecc9ad42ULL;
};

template<class ContainerAllocator>
struct DataType< ::delivery_system::ExceptionHandleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delivery_system/ExceptionHandleResponse";
  }

  static const char* value(const ::delivery_system::ExceptionHandleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delivery_system::ExceptionHandleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 响应：人工确认\n"
"bool confirm_continue       # 是否继续执行任务\n"
"\n"
;
  }

  static const char* value(const ::delivery_system::ExceptionHandleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delivery_system::ExceptionHandleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.confirm_continue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExceptionHandleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delivery_system::ExceptionHandleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delivery_system::ExceptionHandleResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "confirm_continue: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.confirm_continue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELIVERY_SYSTEM_MESSAGE_EXCEPTIONHANDLERESPONSE_H
