// Generated by gencpp from file delivery_system/TaskReportResponse.msg
// DO NOT EDIT!


#ifndef DELIVERY_SYSTEM_MESSAGE_TASKREPORTRESPONSE_H
#define DELIVERY_SYSTEM_MESSAGE_TASKREPORTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delivery_system
{
template <class ContainerAllocator>
struct TaskReportResponse_
{
  typedef TaskReportResponse_<ContainerAllocator> Type;

  TaskReportResponse_()
    : success(false)
    , message()  {
    }
  TaskReportResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::delivery_system::TaskReportResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delivery_system::TaskReportResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TaskReportResponse_

typedef ::delivery_system::TaskReportResponse_<std::allocator<void> > TaskReportResponse;

typedef boost::shared_ptr< ::delivery_system::TaskReportResponse > TaskReportResponsePtr;
typedef boost::shared_ptr< ::delivery_system::TaskReportResponse const> TaskReportResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delivery_system::TaskReportResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delivery_system::TaskReportResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delivery_system::TaskReportResponse_<ContainerAllocator1> & lhs, const ::delivery_system::TaskReportResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delivery_system::TaskReportResponse_<ContainerAllocator1> & lhs, const ::delivery_system::TaskReportResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delivery_system

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delivery_system::TaskReportResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery_system::TaskReportResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery_system::TaskReportResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery_system::TaskReportResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_system::TaskReportResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_system::TaskReportResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delivery_system::TaskReportResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::delivery_system::TaskReportResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::delivery_system::TaskReportResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delivery_system/TaskReportResponse";
  }

  static const char* value(const ::delivery_system::TaskReportResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delivery_system::TaskReportResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 响应：结果\n"
"bool success                # 报告生成是否成功\n"
"string message              # 反馈信息\n"
"\n"
;
  }

  static const char* value(const ::delivery_system::TaskReportResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delivery_system::TaskReportResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskReportResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delivery_system::TaskReportResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delivery_system::TaskReportResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELIVERY_SYSTEM_MESSAGE_TASKREPORTRESPONSE_H
