// Generated by gencpp from file delivery_system/TaskReportRequest.msg
// DO NOT EDIT!


#ifndef DELIVERY_SYSTEM_MESSAGE_TASKREPORTREQUEST_H
#define DELIVERY_SYSTEM_MESSAGE_TASKREPORTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delivery_system
{
template <class ContainerAllocator>
struct TaskReportRequest_
{
  typedef TaskReportRequest_<ContainerAllocator> Type;

  TaskReportRequest_()
    : total_time(0.0)
    , arrived_stations()
    , exceptions()  {
    }
  TaskReportRequest_(const ContainerAllocator& _alloc)
    : total_time(0.0)
    , arrived_stations(_alloc)
    , exceptions(_alloc)  {
  (void)_alloc;
    }



   typedef float _total_time_type;
  _total_time_type total_time;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _arrived_stations_type;
  _arrived_stations_type arrived_stations;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _exceptions_type;
  _exceptions_type exceptions;





  typedef boost::shared_ptr< ::delivery_system::TaskReportRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delivery_system::TaskReportRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TaskReportRequest_

typedef ::delivery_system::TaskReportRequest_<std::allocator<void> > TaskReportRequest;

typedef boost::shared_ptr< ::delivery_system::TaskReportRequest > TaskReportRequestPtr;
typedef boost::shared_ptr< ::delivery_system::TaskReportRequest const> TaskReportRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delivery_system::TaskReportRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delivery_system::TaskReportRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delivery_system::TaskReportRequest_<ContainerAllocator1> & lhs, const ::delivery_system::TaskReportRequest_<ContainerAllocator2> & rhs)
{
  return lhs.total_time == rhs.total_time &&
    lhs.arrived_stations == rhs.arrived_stations &&
    lhs.exceptions == rhs.exceptions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delivery_system::TaskReportRequest_<ContainerAllocator1> & lhs, const ::delivery_system::TaskReportRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delivery_system

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delivery_system::TaskReportRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery_system::TaskReportRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery_system::TaskReportRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery_system::TaskReportRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_system::TaskReportRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_system::TaskReportRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delivery_system::TaskReportRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "02467ad323c5ac2c77cac6918145f45d";
  }

  static const char* value(const ::delivery_system::TaskReportRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x02467ad323c5ac2cULL;
  static const uint64_t static_value2 = 0x77cac6918145f45dULL;
};

template<class ContainerAllocator>
struct DataType< ::delivery_system::TaskReportRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delivery_system/TaskReportRequest";
  }

  static const char* value(const ::delivery_system::TaskReportRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delivery_system::TaskReportRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 请求：任务数据\n"
"float32 total_time          # 总耗时（秒）\n"
"string[] arrived_stations   # 成功到达的站点列表\n"
"string[] exceptions         # 异常记录列表\n"
;
  }

  static const char* value(const ::delivery_system::TaskReportRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delivery_system::TaskReportRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_time);
      stream.next(m.arrived_stations);
      stream.next(m.exceptions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskReportRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delivery_system::TaskReportRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delivery_system::TaskReportRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "total_time: ";
    Printer<float>::stream(s, indent + "  ", v.total_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "arrived_stations: ";
    if (v.arrived_stations.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.arrived_stations.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.arrived_stations[i]);
    }
    if (v.arrived_stations.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "exceptions: ";
    if (v.exceptions.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.exceptions.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.exceptions[i]);
    }
    if (v.exceptions.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELIVERY_SYSTEM_MESSAGE_TASKREPORTREQUEST_H
