// Generated by gencpp from file delivery_system/TaskReport.msg
// DO NOT EDIT!


#ifndef DELIVERY_SYSTEM_MESSAGE_TASKREPORT_H
#define DELIVERY_SYSTEM_MESSAGE_TASKREPORT_H

#include <ros/service_traits.h>


#include <delivery_system/TaskReportRequest.h>
#include <delivery_system/TaskReportResponse.h>


namespace delivery_system
{

struct TaskReport
{

typedef TaskReportRequest Request;
typedef TaskReportResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TaskReport
} // namespace delivery_system


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::delivery_system::TaskReport > {
  static const char* value()
  {
    return "366d446c5045fee0bf1794916e375414";
  }

  static const char* value(const ::delivery_system::TaskReport&) { return value(); }
};

template<>
struct DataType< ::delivery_system::TaskReport > {
  static const char* value()
  {
    return "delivery_system/TaskReport";
  }

  static const char* value(const ::delivery_system::TaskReport&) { return value(); }
};


// service_traits::MD5Sum< ::delivery_system::TaskReportRequest> should match
// service_traits::MD5Sum< ::delivery_system::TaskReport >
template<>
struct MD5Sum< ::delivery_system::TaskReportRequest>
{
  static const char* value()
  {
    return MD5Sum< ::delivery_system::TaskReport >::value();
  }
  static const char* value(const ::delivery_system::TaskReportRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::delivery_system::TaskReportRequest> should match
// service_traits::DataType< ::delivery_system::TaskReport >
template<>
struct DataType< ::delivery_system::TaskReportRequest>
{
  static const char* value()
  {
    return DataType< ::delivery_system::TaskReport >::value();
  }
  static const char* value(const ::delivery_system::TaskReportRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::delivery_system::TaskReportResponse> should match
// service_traits::MD5Sum< ::delivery_system::TaskReport >
template<>
struct MD5Sum< ::delivery_system::TaskReportResponse>
{
  static const char* value()
  {
    return MD5Sum< ::delivery_system::TaskReport >::value();
  }
  static const char* value(const ::delivery_system::TaskReportResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::delivery_system::TaskReportResponse> should match
// service_traits::DataType< ::delivery_system::TaskReport >
template<>
struct DataType< ::delivery_system::TaskReportResponse>
{
  static const char* value()
  {
    return DataType< ::delivery_system::TaskReport >::value();
  }
  static const char* value(const ::delivery_system::TaskReportResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DELIVERY_SYSTEM_MESSAGE_TASKREPORT_H
